version: "3.8"

services:
  api:
    container_name: django_api
    build: ./backend
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/api
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
    