version: "3.8"

services:
  api:
    container_name: django_api
    build: ./backend
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    container_name: postgres_db
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres_db" ]
      interval: 10s
      timeout: 3s
      retries: 2

volumes:
  postgres_data:
    